# Generated by Django 5.2.1 on 2025-06-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Техническая поддержка',
                'verbose_name_plural': 'Техническая поддержка',
            },
        ),
    ]
