# Generated by Django 5.2.1 on 2025-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_supporthelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_namber',
            field=models.CharField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='supporthelp',
            name='support_url',
            field=models.CharField(blank=True, null=True, verbose_name='Укажите ссылку на аккаунт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
