# Generated by Django 5.2.1 on 2025-06-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_user_balance_user_phone_namber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_date_born',
            field=models.CharField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='api_email',
            field=models.CharField(blank=True, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='api_first_name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='api_last_name',
            field=models.CharField(blank=True, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='api_middlename',
            field=models.CharField(blank=True, null=True, verbose_name='Отчество'),
        ),
    ]
