# Generated by Django 5.2.1 on 2025-07-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_user_api_date_born_user_api_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
