# Generated by Django 5.2.1 on 2025-07-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_user_api_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('qr_message_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
